# Generated by Django 6.0.5 on 2026-05-20 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipments', '0004_shipment_label_file_shipmentitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('current_hub', models.CharField(blank=True, max_length=255, null=True)),
                ('estimated_distance_km', models.FloatField()),
                ('estimated_delivery_time', models.DateTimeField()),
                ('is_route_optimized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='shipments.shipment')),
            ],
        ),
    ]
