# Generated by Django 5.2.14 on 2026-05-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_align_models_with_current_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
