# Generated by Django 5.2.14 on 2026-05-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NDR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_awb', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=255)),
                ('attempts', models.IntegerField(default=1)),
                ('merchant_action', models.CharField(choices=[('PENDING', 'Pending'), ('REATTEMPT', 'Reattempt'), ('RTO', 'Return to Origin')], default='PENDING', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='ReturnRequest',
        ),
    ]
