# Generated by Django 5.2.14 on 2026-05-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0002_ndr_delete_returnrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndr',
            name='merchant_action',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REATTEMPT', 'Reattempt'), ('RTO', 'Return To Origin')], default='PENDING', max_length=20),
        ),
    ]
