# Generated by Django 6.0.5 on 2026-05-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='receiver_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='sender_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20),
        ),
    ]
