# Generated by Django on 2026-05-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_merchant_webhookendpoint_user_flags"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyAnalytics",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("total_shipments", models.IntegerField(default=0)),
                ("delivered_shipments", models.IntegerField(default=0)),
                ("failed_shipments", models.IntegerField(default=0)),
                ("rto_shipments", models.IntegerField(default=0)),
                ("total_cod", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("total_revenue", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("analytics_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "merchant",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="accounts.merchant"),
                ),
            ],
            options={
                "ordering": ["-analytics_date"],
                "unique_together": {("merchant", "analytics_date")},
            },
        ),
    ]
